version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 ${DJANGO_APP}.wsgi:application
    volumes:
      - ./vapi:/app
      - ./vapi/secrets:/app/secrets
      - ./scripts:/app/scripts
    ports:
      - "8000:8000"  # Publica el puerto 8000 para pruebas locales
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./vapi:/app
    depends_on:
      - web

volumes:
  postgres_data:
